services:
  chess_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chess_frontend_app
    ports:
      - "8081:8080"
    volumes:
      - ./src:/app/src:cached 
      - ./pom.xml:/app/pom.xml:cached
      - maven-repo:/root/.m2  
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - SPRING_OUTPUT_ANSI_ENABLED=always
    stdin_open: true
    tty: true

volumes:
  maven-repo: