services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chess_frontend_app
    ports:
      - "8081:8080"
    volumes:
      - ./src:/app/src
      - ./target:/app/target 
      - maven-repo:/root/.m2  
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    restart: unless-stopped

volumes:
  maven-repo: